import type { DictionaryKeyEntry } from "./types";

/**
 * Module name that the generated file augments. Centralized so that future
 * refactors (e.g. moving the dictionary key registry to a different package) only
 * touch this constant rather than every consumer's checked-in `.gen.ts`.
 */
export const DICTIONARY_AUGMENT_TARGET = "@vef-framework-react/hooks";

export interface RenderDictionaryKeysOptions {
  /**
   * Config file path (relative to project root) recorded in the file banner
   * for traceability.
   */
  configFile: string;
  /**
   * Module name to augment. Defaults to {@link DICTIONARY_AUGMENT_TARGET}.
   * Overridable for tests and for downstream forks that re-publish the
   * extension point under a different package name.
   */
  augmentTarget?: string;
}

const FILE_BANNER = [
  "/* eslint-disable */",
  "// @ts-nocheck",
  "// noinspection JSUnusedGlobalSymbols",
  "// AUTO-GENERATED by @vef-framework-react/dev (vef gen:dictionary-keys). DO NOT EDIT."
];

/**
 * Render the dictionary keys file content. Pure function for snapshot tests.
 */
export function renderDictionaryKeysFile(
  entries: readonly DictionaryKeyEntry[],
  options: RenderDictionaryKeysOptions
): string {
  const { configFile, augmentTarget = DICTIONARY_AUGMENT_TARGET } = options;
  const lines: string[] = [...FILE_BANNER, `// Source: ${configFile}`, ""];

  if (entries.length === 0) {
    lines.push("export type DictionaryKey = never;");
  } else {
    lines.push("export type DictionaryKey =");

    for (const [index, entry] of entries.entries()) {
      const suffix = index === entries.length - 1 ? ";" : "";

      if (entry.comment) {
        lines.push(`  /** ${escapeComment(entry.comment)} */`);
      }

      lines.push(`  | ${JSON.stringify(entry.key)}${suffix}`);
    }
  }

  lines.push(
    "",
    `declare module ${JSON.stringify(augmentTarget)} {`,
    "  interface Register {",
    "    dictionaryKeys: DictionaryKey;",
    "  }",
    "}",
    ""
  );

  return lines.join("\n");
}

/**
 * Sanitize a string for safe embedding inside a JSDoc `/** ... *\/` block:
 * - collapse whitespace (including U+2028/U+2029 line/paragraph separators
 * that some JS tooling treats as line terminators);
 * - trim;
 * - escape inner comment terminators so the block can't close early.
 */
function escapeComment(text: string): string {
  return text
    .replaceAll(/\s+/g, " ")
    .trim()
    .replaceAll("*/", String.raw`*\/`);
}
