import type { ReactNode } from "react";

import { createFileRoute } from "@tanstack/react-router";
import { Page, Select, Stack, Text, useCodeSetOptionsSelect } from "@vef-framework-react/components";

export const Route = createFileRoute("/_layout/sys/code-set-demo")({
  component: CodeSetDemoPage
});

function CodeSetDemoPage(): ReactNode {
  // Positive: both keys exist in the generated CodeSetKey union, so the
  // call type-checks and IDE autocomplete suggests valid keys.
  const { gender: genderSelectProps, menuType: menuTypeSelectProps } = useCodeSetOptionsSelect({
    gender: "sys.user.gender",
    menuType: "sys.menu.type"
  });

  // Negative compile-fail guard: a key outside the union must be rejected.
  // The `@ts-expect-error` directive will fail if the augmentation is broken,
  // making this assertion serve as a regression test for the augmentation.
  // @ts-expect-error -- "not.a.real.key" is not a member of CodeSetKey
  useCodeSetOptionsSelect({ rejected: "not.a.real.key" });

  return (
    <Page scrollable>
      <Stack gap="medium">
        <Text>
          This page demonstrates the typed `CodeSetKey` union generated by
          `vef gen:code-set-keys`. Inspect the source to see the positive
          and compile-fail cases.
        </Text>

        <Stack>
          <Text strong>sys.user.gender</Text>
          <Select {...genderSelectProps} style={{ width: 240 }} />
        </Stack>

        <Stack>
          <Text strong>sys.menu.type</Text>
          <Select {...menuTypeSelectProps} style={{ width: 240 }} />
        </Stack>
      </Stack>
    </Page>
  );
}
