/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { createRouter } from "@vef-framework-react/starter";

import { routerContext as context } from "./context";

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../pages/__root";
import { Route as LayoutRouteRouteImport } from "./../pages/_layout/route";
import { Route as CommonSelectAppRouteImport } from "./../pages/_common/select-app";
import { Route as CommonLoginRouteImport } from "./../pages/_common/login";
import { Route as CommonAccessDeniedRouteImport } from "./../pages/_common/access-denied";
import { Route as LayoutIndexRouteRouteImport } from "./../pages/_layout/index/route";
import { Route as LayoutSysSerialNoRuleRouteRouteImport } from "./../pages/_layout/sys/serial-no-rule/route";
import { Route as LayoutSysMonitorRouteRouteImport } from "./../pages/_layout/sys/monitor/route";
import { Route as LayoutSysLoginLogRouteRouteImport } from "./../pages/_layout/sys/login-log/route";
import { Route as LayoutSysFormEditorRouteRouteImport } from "./../pages/_layout/sys/form-editor/route";
import { Route as LayoutSysFlowDesignerWizardRouteRouteImport } from "./../pages/_layout/sys/flow-designer-wizard/route";
import { Route as LayoutSysEditableTableDemoRouteRouteImport } from "./../pages/_layout/sys/editable-table-demo/route";
import { Route as LayoutSysDictionaryItemRouteRouteImport } from "./../pages/_layout/sys/dictionary-item/route";
import { Route as LayoutSysDictionaryDemoRouteRouteImport } from "./../pages/_layout/sys/dictionary-demo/route";
import { Route as LayoutSysDictionaryRouteRouteImport } from "./../pages/_layout/sys/dictionary/route";
import { Route as LayoutSysConfigDefinitionRouteRouteImport } from "./../pages/_layout/sys/config-definition/route";
import { Route as LayoutSysConfigRouteRouteImport } from "./../pages/_layout/sys/config/route";
import { Route as LayoutSysAuditLogRouteRouteImport } from "./../pages/_layout/sys/audit-log/route";
import { Route as LayoutSysApprovalTaskDemoRouteRouteImport } from "./../pages/_layout/sys/approval-task-demo/route";
import { Route as LayoutSysApprovalFlowEditorRouteRouteImport } from "./../pages/_layout/sys/approval-flow-editor/route";
import { Route as LayoutSysAppRouteRouteImport } from "./../pages/_layout/sys/app/route";
import { Route as LayoutMdStaffRouteRouteImport } from "./../pages/_layout/md/staff/route";
import { Route as LayoutMdOrganizationRouteRouteImport } from "./../pages/_layout/md/organization/route";
import { Route as LayoutMdIdMappingRouteRouteImport } from "./../pages/_layout/md/id-mapping/route";
import { Route as LayoutMdDistrictRouteRouteImport } from "./../pages/_layout/md/district/route";
import { Route as LayoutMdDepartmentRouteRouteImport } from "./../pages/_layout/md/department/route";
import { Route as LayoutAuthUserRouteRouteImport } from "./../pages/_layout/auth/user/route";
import { Route as LayoutAuthRoleRouteRouteImport } from "./../pages/_layout/auth/role/route";
import { Route as LayoutAuthMenuRouteRouteImport } from "./../pages/_layout/auth/menu/route";

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any);
const CommonSelectAppRoute = CommonSelectAppRouteImport.update({
  id: "/_common/select-app",
  path: "/select-app",
  getParentRoute: () => rootRouteImport,
} as any);
const CommonLoginRoute = CommonLoginRouteImport.update({
  id: "/_common/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const CommonAccessDeniedRoute = CommonAccessDeniedRouteImport.update({
  id: "/_common/access-denied",
  path: "/access-denied",
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRouteRoute = LayoutIndexRouteRouteImport.update({
  id: "/",
  path: "",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutSysSerialNoRuleRouteRoute =
  LayoutSysSerialNoRuleRouteRouteImport.update({
    id: "/sys/serial-no-rule",
    path: "/sys/serial-no-rule",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysMonitorRouteRoute = LayoutSysMonitorRouteRouteImport.update({
  id: "/sys/monitor",
  path: "/sys/monitor",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutSysLoginLogRouteRoute = LayoutSysLoginLogRouteRouteImport.update({
  id: "/sys/login-log",
  path: "/sys/login-log",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutSysFormEditorRouteRoute =
  LayoutSysFormEditorRouteRouteImport.update({
    id: "/sys/form-editor",
    path: "/sys/form-editor",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysFlowDesignerWizardRouteRoute =
  LayoutSysFlowDesignerWizardRouteRouteImport.update({
    id: "/sys/flow-designer-wizard",
    path: "/sys/flow-designer-wizard",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysEditableTableDemoRouteRoute =
  LayoutSysEditableTableDemoRouteRouteImport.update({
    id: "/sys/editable-table-demo",
    path: "/sys/editable-table-demo",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysDictionaryItemRouteRoute =
  LayoutSysDictionaryItemRouteRouteImport.update({
    id: "/sys/dictionary-item",
    path: "/sys/dictionary-item",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysDictionaryDemoRouteRoute =
  LayoutSysDictionaryDemoRouteRouteImport.update({
    id: "/sys/dictionary-demo",
    path: "/sys/dictionary-demo",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysDictionaryRouteRoute =
  LayoutSysDictionaryRouteRouteImport.update({
    id: "/sys/dictionary",
    path: "/sys/dictionary",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysConfigDefinitionRouteRoute =
  LayoutSysConfigDefinitionRouteRouteImport.update({
    id: "/sys/config-definition",
    path: "/sys/config-definition",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysConfigRouteRoute = LayoutSysConfigRouteRouteImport.update({
  id: "/sys/config",
  path: "/sys/config",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutSysAuditLogRouteRoute = LayoutSysAuditLogRouteRouteImport.update({
  id: "/sys/audit-log",
  path: "/sys/audit-log",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutSysApprovalTaskDemoRouteRoute =
  LayoutSysApprovalTaskDemoRouteRouteImport.update({
    id: "/sys/approval-task-demo",
    path: "/sys/approval-task-demo",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysApprovalFlowEditorRouteRoute =
  LayoutSysApprovalFlowEditorRouteRouteImport.update({
    id: "/sys/approval-flow-editor",
    path: "/sys/approval-flow-editor",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutSysAppRouteRoute = LayoutSysAppRouteRouteImport.update({
  id: "/sys/app",
  path: "/sys/app",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutMdStaffRouteRoute = LayoutMdStaffRouteRouteImport.update({
  id: "/md/staff",
  path: "/md/staff",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutMdOrganizationRouteRoute =
  LayoutMdOrganizationRouteRouteImport.update({
    id: "/md/organization",
    path: "/md/organization",
    getParentRoute: () => LayoutRouteRoute,
  } as any);
const LayoutMdIdMappingRouteRoute = LayoutMdIdMappingRouteRouteImport.update({
  id: "/md/id-mapping",
  path: "/md/id-mapping",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutMdDistrictRouteRoute = LayoutMdDistrictRouteRouteImport.update({
  id: "/md/district",
  path: "/md/district",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutMdDepartmentRouteRoute = LayoutMdDepartmentRouteRouteImport.update({
  id: "/md/department",
  path: "/md/department",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutAuthUserRouteRoute = LayoutAuthUserRouteRouteImport.update({
  id: "/auth/user",
  path: "/auth/user",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutAuthRoleRouteRoute = LayoutAuthRoleRouteRouteImport.update({
  id: "/auth/role",
  path: "/auth/role",
  getParentRoute: () => LayoutRouteRoute,
} as any);
const LayoutAuthMenuRouteRoute = LayoutAuthMenuRouteRouteImport.update({
  id: "/auth/menu",
  path: "/auth/menu",
  getParentRoute: () => LayoutRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRouteRoute;
  "/access-denied": typeof CommonAccessDeniedRoute;
  "/login": typeof CommonLoginRoute;
  "/select-app": typeof CommonSelectAppRoute;
  "/auth/menu": typeof LayoutAuthMenuRouteRoute;
  "/auth/role": typeof LayoutAuthRoleRouteRoute;
  "/auth/user": typeof LayoutAuthUserRouteRoute;
  "/md/department": typeof LayoutMdDepartmentRouteRoute;
  "/md/district": typeof LayoutMdDistrictRouteRoute;
  "/md/id-mapping": typeof LayoutMdIdMappingRouteRoute;
  "/md/organization": typeof LayoutMdOrganizationRouteRoute;
  "/md/staff": typeof LayoutMdStaffRouteRoute;
  "/sys/app": typeof LayoutSysAppRouteRoute;
  "/sys/approval-flow-editor": typeof LayoutSysApprovalFlowEditorRouteRoute;
  "/sys/approval-task-demo": typeof LayoutSysApprovalTaskDemoRouteRoute;
  "/sys/audit-log": typeof LayoutSysAuditLogRouteRoute;
  "/sys/config": typeof LayoutSysConfigRouteRoute;
  "/sys/config-definition": typeof LayoutSysConfigDefinitionRouteRoute;
  "/sys/dictionary": typeof LayoutSysDictionaryRouteRoute;
  "/sys/dictionary-demo": typeof LayoutSysDictionaryDemoRouteRoute;
  "/sys/dictionary-item": typeof LayoutSysDictionaryItemRouteRoute;
  "/sys/editable-table-demo": typeof LayoutSysEditableTableDemoRouteRoute;
  "/sys/flow-designer-wizard": typeof LayoutSysFlowDesignerWizardRouteRoute;
  "/sys/form-editor": typeof LayoutSysFormEditorRouteRoute;
  "/sys/login-log": typeof LayoutSysLoginLogRouteRoute;
  "/sys/monitor": typeof LayoutSysMonitorRouteRoute;
  "/sys/serial-no-rule": typeof LayoutSysSerialNoRuleRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof LayoutIndexRouteRoute;
  "/access-denied": typeof CommonAccessDeniedRoute;
  "/login": typeof CommonLoginRoute;
  "/select-app": typeof CommonSelectAppRoute;
  "/auth/menu": typeof LayoutAuthMenuRouteRoute;
  "/auth/role": typeof LayoutAuthRoleRouteRoute;
  "/auth/user": typeof LayoutAuthUserRouteRoute;
  "/md/department": typeof LayoutMdDepartmentRouteRoute;
  "/md/district": typeof LayoutMdDistrictRouteRoute;
  "/md/id-mapping": typeof LayoutMdIdMappingRouteRoute;
  "/md/organization": typeof LayoutMdOrganizationRouteRoute;
  "/md/staff": typeof LayoutMdStaffRouteRoute;
  "/sys/app": typeof LayoutSysAppRouteRoute;
  "/sys/approval-flow-editor": typeof LayoutSysApprovalFlowEditorRouteRoute;
  "/sys/approval-task-demo": typeof LayoutSysApprovalTaskDemoRouteRoute;
  "/sys/audit-log": typeof LayoutSysAuditLogRouteRoute;
  "/sys/config": typeof LayoutSysConfigRouteRoute;
  "/sys/config-definition": typeof LayoutSysConfigDefinitionRouteRoute;
  "/sys/dictionary": typeof LayoutSysDictionaryRouteRoute;
  "/sys/dictionary-demo": typeof LayoutSysDictionaryDemoRouteRoute;
  "/sys/dictionary-item": typeof LayoutSysDictionaryItemRouteRoute;
  "/sys/editable-table-demo": typeof LayoutSysEditableTableDemoRouteRoute;
  "/sys/flow-designer-wizard": typeof LayoutSysFlowDesignerWizardRouteRoute;
  "/sys/form-editor": typeof LayoutSysFormEditorRouteRoute;
  "/sys/login-log": typeof LayoutSysLoginLogRouteRoute;
  "/sys/monitor": typeof LayoutSysMonitorRouteRoute;
  "/sys/serial-no-rule": typeof LayoutSysSerialNoRuleRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_layout": typeof LayoutRouteRouteWithChildren;
  "/_layout/": typeof LayoutIndexRouteRoute;
  "/_common/access-denied": typeof CommonAccessDeniedRoute;
  "/_common/login": typeof CommonLoginRoute;
  "/_common/select-app": typeof CommonSelectAppRoute;
  "/_layout/auth/menu": typeof LayoutAuthMenuRouteRoute;
  "/_layout/auth/role": typeof LayoutAuthRoleRouteRoute;
  "/_layout/auth/user": typeof LayoutAuthUserRouteRoute;
  "/_layout/md/department": typeof LayoutMdDepartmentRouteRoute;
  "/_layout/md/district": typeof LayoutMdDistrictRouteRoute;
  "/_layout/md/id-mapping": typeof LayoutMdIdMappingRouteRoute;
  "/_layout/md/organization": typeof LayoutMdOrganizationRouteRoute;
  "/_layout/md/staff": typeof LayoutMdStaffRouteRoute;
  "/_layout/sys/app": typeof LayoutSysAppRouteRoute;
  "/_layout/sys/approval-flow-editor": typeof LayoutSysApprovalFlowEditorRouteRoute;
  "/_layout/sys/approval-task-demo": typeof LayoutSysApprovalTaskDemoRouteRoute;
  "/_layout/sys/audit-log": typeof LayoutSysAuditLogRouteRoute;
  "/_layout/sys/config": typeof LayoutSysConfigRouteRoute;
  "/_layout/sys/config-definition": typeof LayoutSysConfigDefinitionRouteRoute;
  "/_layout/sys/dictionary": typeof LayoutSysDictionaryRouteRoute;
  "/_layout/sys/dictionary-demo": typeof LayoutSysDictionaryDemoRouteRoute;
  "/_layout/sys/dictionary-item": typeof LayoutSysDictionaryItemRouteRoute;
  "/_layout/sys/editable-table-demo": typeof LayoutSysEditableTableDemoRouteRoute;
  "/_layout/sys/flow-designer-wizard": typeof LayoutSysFlowDesignerWizardRouteRoute;
  "/_layout/sys/form-editor": typeof LayoutSysFormEditorRouteRoute;
  "/_layout/sys/login-log": typeof LayoutSysLoginLogRouteRoute;
  "/_layout/sys/monitor": typeof LayoutSysMonitorRouteRoute;
  "/_layout/sys/serial-no-rule": typeof LayoutSysSerialNoRuleRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/access-denied"
    | "/login"
    | "/select-app"
    | "/auth/menu"
    | "/auth/role"
    | "/auth/user"
    | "/md/department"
    | "/md/district"
    | "/md/id-mapping"
    | "/md/organization"
    | "/md/staff"
    | "/sys/app"
    | "/sys/approval-flow-editor"
    | "/sys/approval-task-demo"
    | "/sys/audit-log"
    | "/sys/config"
    | "/sys/config-definition"
    | "/sys/dictionary"
    | "/sys/dictionary-demo"
    | "/sys/dictionary-item"
    | "/sys/editable-table-demo"
    | "/sys/flow-designer-wizard"
    | "/sys/form-editor"
    | "/sys/login-log"
    | "/sys/monitor"
    | "/sys/serial-no-rule";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/access-denied"
    | "/login"
    | "/select-app"
    | "/auth/menu"
    | "/auth/role"
    | "/auth/user"
    | "/md/department"
    | "/md/district"
    | "/md/id-mapping"
    | "/md/organization"
    | "/md/staff"
    | "/sys/app"
    | "/sys/approval-flow-editor"
    | "/sys/approval-task-demo"
    | "/sys/audit-log"
    | "/sys/config"
    | "/sys/config-definition"
    | "/sys/dictionary"
    | "/sys/dictionary-demo"
    | "/sys/dictionary-item"
    | "/sys/editable-table-demo"
    | "/sys/flow-designer-wizard"
    | "/sys/form-editor"
    | "/sys/login-log"
    | "/sys/monitor"
    | "/sys/serial-no-rule";
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/"
    | "/_common/access-denied"
    | "/_common/login"
    | "/_common/select-app"
    | "/_layout/auth/menu"
    | "/_layout/auth/role"
    | "/_layout/auth/user"
    | "/_layout/md/department"
    | "/_layout/md/district"
    | "/_layout/md/id-mapping"
    | "/_layout/md/organization"
    | "/_layout/md/staff"
    | "/_layout/sys/app"
    | "/_layout/sys/approval-flow-editor"
    | "/_layout/sys/approval-task-demo"
    | "/_layout/sys/audit-log"
    | "/_layout/sys/config"
    | "/_layout/sys/config-definition"
    | "/_layout/sys/dictionary"
    | "/_layout/sys/dictionary-demo"
    | "/_layout/sys/dictionary-item"
    | "/_layout/sys/editable-table-demo"
    | "/_layout/sys/flow-designer-wizard"
    | "/_layout/sys/form-editor"
    | "/_layout/sys/login-log"
    | "/_layout/sys/monitor"
    | "/_layout/sys/serial-no-rule";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren;
  CommonAccessDeniedRoute: typeof CommonAccessDeniedRoute;
  CommonLoginRoute: typeof CommonLoginRoute;
  CommonSelectAppRoute: typeof CommonSelectAppRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_common/select-app": {
      id: "/_common/select-app";
      path: "/select-app";
      fullPath: "/select-app";
      preLoaderRoute: typeof CommonSelectAppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_common/login": {
      id: "/_common/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof CommonLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_common/access-denied": {
      id: "/_common/access-denied";
      path: "/access-denied";
      fullPath: "/access-denied";
      preLoaderRoute: typeof CommonAccessDeniedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/serial-no-rule": {
      id: "/_layout/sys/serial-no-rule";
      path: "/sys/serial-no-rule";
      fullPath: "/sys/serial-no-rule";
      preLoaderRoute: typeof LayoutSysSerialNoRuleRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/monitor": {
      id: "/_layout/sys/monitor";
      path: "/sys/monitor";
      fullPath: "/sys/monitor";
      preLoaderRoute: typeof LayoutSysMonitorRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/login-log": {
      id: "/_layout/sys/login-log";
      path: "/sys/login-log";
      fullPath: "/sys/login-log";
      preLoaderRoute: typeof LayoutSysLoginLogRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/form-editor": {
      id: "/_layout/sys/form-editor";
      path: "/sys/form-editor";
      fullPath: "/sys/form-editor";
      preLoaderRoute: typeof LayoutSysFormEditorRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/flow-designer-wizard": {
      id: "/_layout/sys/flow-designer-wizard";
      path: "/sys/flow-designer-wizard";
      fullPath: "/sys/flow-designer-wizard";
      preLoaderRoute: typeof LayoutSysFlowDesignerWizardRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/editable-table-demo": {
      id: "/_layout/sys/editable-table-demo";
      path: "/sys/editable-table-demo";
      fullPath: "/sys/editable-table-demo";
      preLoaderRoute: typeof LayoutSysEditableTableDemoRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/dictionary-item": {
      id: "/_layout/sys/dictionary-item";
      path: "/sys/dictionary-item";
      fullPath: "/sys/dictionary-item";
      preLoaderRoute: typeof LayoutSysDictionaryItemRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/dictionary-demo": {
      id: "/_layout/sys/dictionary-demo";
      path: "/sys/dictionary-demo";
      fullPath: "/sys/dictionary-demo";
      preLoaderRoute: typeof LayoutSysDictionaryDemoRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/dictionary": {
      id: "/_layout/sys/dictionary";
      path: "/sys/dictionary";
      fullPath: "/sys/dictionary";
      preLoaderRoute: typeof LayoutSysDictionaryRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/config-definition": {
      id: "/_layout/sys/config-definition";
      path: "/sys/config-definition";
      fullPath: "/sys/config-definition";
      preLoaderRoute: typeof LayoutSysConfigDefinitionRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/config": {
      id: "/_layout/sys/config";
      path: "/sys/config";
      fullPath: "/sys/config";
      preLoaderRoute: typeof LayoutSysConfigRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/audit-log": {
      id: "/_layout/sys/audit-log";
      path: "/sys/audit-log";
      fullPath: "/sys/audit-log";
      preLoaderRoute: typeof LayoutSysAuditLogRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/approval-task-demo": {
      id: "/_layout/sys/approval-task-demo";
      path: "/sys/approval-task-demo";
      fullPath: "/sys/approval-task-demo";
      preLoaderRoute: typeof LayoutSysApprovalTaskDemoRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/approval-flow-editor": {
      id: "/_layout/sys/approval-flow-editor";
      path: "/sys/approval-flow-editor";
      fullPath: "/sys/approval-flow-editor";
      preLoaderRoute: typeof LayoutSysApprovalFlowEditorRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/sys/app": {
      id: "/_layout/sys/app";
      path: "/sys/app";
      fullPath: "/sys/app";
      preLoaderRoute: typeof LayoutSysAppRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/md/staff": {
      id: "/_layout/md/staff";
      path: "/md/staff";
      fullPath: "/md/staff";
      preLoaderRoute: typeof LayoutMdStaffRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/md/organization": {
      id: "/_layout/md/organization";
      path: "/md/organization";
      fullPath: "/md/organization";
      preLoaderRoute: typeof LayoutMdOrganizationRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/md/id-mapping": {
      id: "/_layout/md/id-mapping";
      path: "/md/id-mapping";
      fullPath: "/md/id-mapping";
      preLoaderRoute: typeof LayoutMdIdMappingRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/md/district": {
      id: "/_layout/md/district";
      path: "/md/district";
      fullPath: "/md/district";
      preLoaderRoute: typeof LayoutMdDistrictRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/md/department": {
      id: "/_layout/md/department";
      path: "/md/department";
      fullPath: "/md/department";
      preLoaderRoute: typeof LayoutMdDepartmentRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/auth/user": {
      id: "/_layout/auth/user";
      path: "/auth/user";
      fullPath: "/auth/user";
      preLoaderRoute: typeof LayoutAuthUserRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/auth/role": {
      id: "/_layout/auth/role";
      path: "/auth/role";
      fullPath: "/auth/role";
      preLoaderRoute: typeof LayoutAuthRoleRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
    "/_layout/auth/menu": {
      id: "/_layout/auth/menu";
      path: "/auth/menu";
      fullPath: "/auth/menu";
      preLoaderRoute: typeof LayoutAuthMenuRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRouteRoute: typeof LayoutIndexRouteRoute;
  LayoutAuthMenuRouteRoute: typeof LayoutAuthMenuRouteRoute;
  LayoutAuthRoleRouteRoute: typeof LayoutAuthRoleRouteRoute;
  LayoutAuthUserRouteRoute: typeof LayoutAuthUserRouteRoute;
  LayoutMdDepartmentRouteRoute: typeof LayoutMdDepartmentRouteRoute;
  LayoutMdDistrictRouteRoute: typeof LayoutMdDistrictRouteRoute;
  LayoutMdIdMappingRouteRoute: typeof LayoutMdIdMappingRouteRoute;
  LayoutMdOrganizationRouteRoute: typeof LayoutMdOrganizationRouteRoute;
  LayoutMdStaffRouteRoute: typeof LayoutMdStaffRouteRoute;
  LayoutSysAppRouteRoute: typeof LayoutSysAppRouteRoute;
  LayoutSysApprovalFlowEditorRouteRoute: typeof LayoutSysApprovalFlowEditorRouteRoute;
  LayoutSysApprovalTaskDemoRouteRoute: typeof LayoutSysApprovalTaskDemoRouteRoute;
  LayoutSysAuditLogRouteRoute: typeof LayoutSysAuditLogRouteRoute;
  LayoutSysConfigRouteRoute: typeof LayoutSysConfigRouteRoute;
  LayoutSysConfigDefinitionRouteRoute: typeof LayoutSysConfigDefinitionRouteRoute;
  LayoutSysDictionaryRouteRoute: typeof LayoutSysDictionaryRouteRoute;
  LayoutSysDictionaryDemoRouteRoute: typeof LayoutSysDictionaryDemoRouteRoute;
  LayoutSysDictionaryItemRouteRoute: typeof LayoutSysDictionaryItemRouteRoute;
  LayoutSysEditableTableDemoRouteRoute: typeof LayoutSysEditableTableDemoRouteRoute;
  LayoutSysFlowDesignerWizardRouteRoute: typeof LayoutSysFlowDesignerWizardRouteRoute;
  LayoutSysFormEditorRouteRoute: typeof LayoutSysFormEditorRouteRoute;
  LayoutSysLoginLogRouteRoute: typeof LayoutSysLoginLogRouteRoute;
  LayoutSysMonitorRouteRoute: typeof LayoutSysMonitorRouteRoute;
  LayoutSysSerialNoRuleRouteRoute: typeof LayoutSysSerialNoRuleRouteRoute;
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRouteRoute: LayoutIndexRouteRoute,
  LayoutAuthMenuRouteRoute: LayoutAuthMenuRouteRoute,
  LayoutAuthRoleRouteRoute: LayoutAuthRoleRouteRoute,
  LayoutAuthUserRouteRoute: LayoutAuthUserRouteRoute,
  LayoutMdDepartmentRouteRoute: LayoutMdDepartmentRouteRoute,
  LayoutMdDistrictRouteRoute: LayoutMdDistrictRouteRoute,
  LayoutMdIdMappingRouteRoute: LayoutMdIdMappingRouteRoute,
  LayoutMdOrganizationRouteRoute: LayoutMdOrganizationRouteRoute,
  LayoutMdStaffRouteRoute: LayoutMdStaffRouteRoute,
  LayoutSysAppRouteRoute: LayoutSysAppRouteRoute,
  LayoutSysApprovalFlowEditorRouteRoute: LayoutSysApprovalFlowEditorRouteRoute,
  LayoutSysApprovalTaskDemoRouteRoute: LayoutSysApprovalTaskDemoRouteRoute,
  LayoutSysAuditLogRouteRoute: LayoutSysAuditLogRouteRoute,
  LayoutSysConfigRouteRoute: LayoutSysConfigRouteRoute,
  LayoutSysConfigDefinitionRouteRoute: LayoutSysConfigDefinitionRouteRoute,
  LayoutSysDictionaryRouteRoute: LayoutSysDictionaryRouteRoute,
  LayoutSysDictionaryDemoRouteRoute: LayoutSysDictionaryDemoRouteRoute,
  LayoutSysDictionaryItemRouteRoute: LayoutSysDictionaryItemRouteRoute,
  LayoutSysEditableTableDemoRouteRoute: LayoutSysEditableTableDemoRouteRoute,
  LayoutSysFlowDesignerWizardRouteRoute: LayoutSysFlowDesignerWizardRouteRoute,
  LayoutSysFormEditorRouteRoute: LayoutSysFormEditorRouteRoute,
  LayoutSysLoginLogRouteRoute: LayoutSysLoginLogRouteRoute,
  LayoutSysMonitorRouteRoute: LayoutSysMonitorRouteRoute,
  LayoutSysSerialNoRuleRouteRoute: LayoutSysSerialNoRuleRouteRoute,
};

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  CommonAccessDeniedRoute: CommonAccessDeniedRoute,
  CommonLoginRoute: CommonLoginRoute,
  CommonSelectAppRoute: CommonSelectAppRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

const router = createRouter({
  history: "browser",
  routeTree,
  context,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

export default router;
