/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { createRouter } from "@vef-framework-react/starter";

import { routerContext as context } from "./context";

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../pages/__root";
import { Route as LayoutRouteRouteImport } from "./../pages/_layout/route";
import { Route as CommonLoginRouteImport } from "./../pages/_common/login";
import { Route as CommonAccessDeniedRouteImport } from "./../pages/_common/access-denied";
import { Route as LayoutIndexRouteRouteImport } from "./../pages/_layout/index/route";

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any);
const CommonLoginRoute = CommonLoginRouteImport.update({
  id: "/_common/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const CommonAccessDeniedRoute = CommonAccessDeniedRouteImport.update({
  id: "/_common/access-denied",
  path: "/access-denied",
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRouteRoute = LayoutIndexRouteRouteImport.update({
  id: "/",
  path: "",
  getParentRoute: () => LayoutRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRouteRoute;
  "/access-denied": typeof CommonAccessDeniedRoute;
  "/login": typeof CommonLoginRoute;
}
export interface FileRoutesByTo {
  "/": typeof LayoutIndexRouteRoute;
  "/access-denied": typeof CommonAccessDeniedRoute;
  "/login": typeof CommonLoginRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_layout": typeof LayoutRouteRouteWithChildren;
  "/_layout/": typeof LayoutIndexRouteRoute;
  "/_common/access-denied": typeof CommonAccessDeniedRoute;
  "/_common/login": typeof CommonLoginRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/access-denied" | "/login";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/access-denied" | "/login";
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/"
    | "/_common/access-denied"
    | "/_common/login";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren;
  CommonLoginRoute: typeof CommonLoginRoute;
  CommonAccessDeniedRoute: typeof CommonAccessDeniedRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_common/login": {
      id: "/_common/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof CommonLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_common/access-denied": {
      id: "/_common/access-denied";
      path: "/access-denied";
      fullPath: "/access-denied";
      preLoaderRoute: typeof CommonAccessDeniedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexRouteRouteImport;
      parentRoute: typeof LayoutRouteRoute;
    };
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRouteRoute: typeof LayoutIndexRouteRoute;
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRouteRoute: LayoutIndexRouteRoute,
};

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  CommonLoginRoute: CommonLoginRoute,
  CommonAccessDeniedRoute: CommonAccessDeniedRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

const router = createRouter({
  history: "browser",
  routeTree,
  context,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

export default router;
