/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// AUTO-GENERATED by @vef-framework-react/dev (vef gen:dictionary-keys). DO NOT EDIT.
// Source: code-generation.config.ts

export type DictionaryKey =
  /** 通用性别 */
  | "common.gender"
  /** 科室级别 */
  | "md.department.level"
  /** 科室类型 */
  | "md.department.type"
  /** 行政区级别 */
  | "md.district.level"
  /** 性别限制 */
  | "md.gender_limit"
  /** 外部应用 */
  | "md.id_mapping.external_app"
  /** 医院等级 */
  | "md.organization.hospital_level"
  /** 机构类型 */
  | "md.organization.type"
  /** 员工类别 */
  | "md.staff.category"
  /** 员工性别 */
  | "md.staff.gender"
  /** 员工证件类型 */
  | "md.staff.id_type"
  /** 员工职务 */
  | "md.staff.position"
  /** 员工专业角色 */
  | "md.staff.professional_role"
  /** 员工职称 */
  | "md.staff.professional_title"
  /** 员工状态 */
  | "md.staff.status"
  /** 配置分类 */
  | "sys.config_definition.category"
  /** 配置值类型 */
  | "sys.config_definition.value_type"
  /** 数据源类型 */
  | "sys.data_source.type"
  /** 菜单类型 */
  | "sys.menu.type"
  /** 流水号日期格式 */
  | "sys.serial_no_rule.date_format"
  /** 流水号重置周期 */
  | "sys.serial_no_rule.reset_cycle"
  /** 系统用户性别 */
  | "sys.user.gender";

declare module "@vef-framework-react/hooks" {
  interface Register {
    dictionaryKeys: DictionaryKey;
  }
}
