import { always } from "radashi";

export const alwaysTrue = always(true);
export const alwaysFalse = always(false);

export { klona as cloneDeep } from "klona";
export { parse as decodeQueryString, stringify as encodeQueryString } from "qs";

export {
  always,
  assign,
  camel as camelCase,
  capitalize,
  cluster,
  debounce,
  first,
  get,
  isArray,
  isBigInt,
  isBoolean,
  isDate,
  isEmpty,
  isError,
  isFloat,
  isFunction,
  isInt,
  isIntString,
  isMap,
  isNullish,
  isNumber,
  isObject,
  isPlainObject,
  isPrimitive,
  isPromise,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  isUndefined,
  isWeakMap,
  isWeakSet,
  dash as kebabCase,
  last,
  max,
  memo as memoize,
  min,
  noop,
  omit,
  once,
  pascal as pascalCase,
  pick,
  set,
  similarity,
  snake as snakeCase,
  sum,
  template,
  throttle,
  toFloat,
  toInt,
  trim,
  unique
} from "radashi";
